---
title: "Data Management"
format: html
editor: visual
css: www/quarto-style.css
---

The FOSS provides federal fisheries data in an organized manner. Across landings, processed products, and trade, the FOSS provides the value at time of sale (i.e., nominal value) and volume (in imperial units) of the product. Export and import data provide the specific city and state of the port of entry; commercial landings data provide the state where fishers landed the catch; but processed products in the FOSS do not contain any geographic data. Also, while each data set provides some resolution of the species that comprise(s) most products (some products report no species), the data sets are not uniform in reporting species. These inconsistencies collectively motivate standardization of federal fisheries data. We performed most of our data management and engineering effort using R (R Core Team, 2023) and tidyverse packages (Wickham et al., 2019).

The FOSS reports value of landings, processed products, and trade as nominal values, which hinders analysis of revenue and price temporal dynamics. We standardized value metrics across all data sets by adjusting values for inflation using a Gross Domestic Product: Implicit Price Deflator (GDPDEF) index from the [Federal Reserve Bank of St. Louis](https://fred.stlouisfed.org/series/GDPDEF). We set 2024 as the base year of the GDPDEF (thus 2024 values are the same as nominal) as it is the most recent full year of data collected and reflects the most recent values and thus prices in the modern market. We averaged the GDPDEF index on an annual frequency to match our data aggregation effort.

Separately, the FOSS reports volumes differently depending on the data source. Trade and processed product volumes are reported in product weight, or the weight of the product post processing, while commercial landings volumes are reported in round weight, or the volume of the fish without processing applied. For metrics that directly compare volumes between trade and commercial landings (Apparent Supply, e.g.), these weights discrepencies should be reconciled.

Our effort to consolidate the round and product weights among data sources involved converting product weights of traded products to round weights. Converting product weight to round weight requires a conversion factor, or a ratio specific to types of products (canned pollock, lobster claws, etc.). We used conversion factors calculated by the European Market Observatory for Fisheries and Aquaculture Products (EUMOFA). We matched conversion factors to appropriate trade products by searching for keywords in product descriptions, such as species names and product conditions (frozen, canned, e.g.). Much of our effort derived from [Steinkruger et al.'s](https://github.com/kaitlyn-c-lee/seafood-traceability-design) effort to match conversion factors to HTS codes in 2024. See 'Metrics' for more information on converting product weight to round weight. 

Additionally, processed products and landings report in imperial units (pounds) while exports and imports report in metric units (kilograms). We standardized all datasets to include volume quantities in both imperial and metric units by converting pounds to kilograms and vice versa. Also, due to the large quantity of volume either traded, processed, or landed, we convert quantities to metric tons (metric units) and short tons (imperial units). For clarification, there are two types of tons in the imperial unit system: a long ton (also known as an imperial ton) is equal to 2,240 pounds, whereas a short ton (also known as a US ton) is equal to 2,000 pounds. We chose the latter due to its simplicity in conversion and ease of qualitative comparison in figures relative to long tons.
