---
title: "Regional Consolidation"
format: html
editor: visual
---

The inherent management of most domestic fisheries at a regional scale warrants a need to provide geographic resolution to federal fisheries data. Since [the first year of FEUS], the NOAA Office of Science & Technology has released the [Fisheries Economics of the United States report](https://www.fisheries.noaa.gov/national/sustainable-fisheries/fisheries-economics-united-states) (FEUS), a Technical Memorandum that describes and analyzes fisheries data through an economic lens. The FEUS analyzes trends in fisheries data both at a national and regional level, organizing data from 23 coastal states into seven management regions: New England (ME, NH, MA, CT, RI), Mid-Atlantic (NY, NJ, DE, MD, VA, DC), South Atlantic (NC, SC, GA, East-FL), Gulf (West-FL, AL, MI, LA, TX), Pacific (WA, OR, CA), North Pacific (AK) and Western Pacific (HI). We follow this regional organization save for some distinctions: in the Mid-Atlantic, we include the District of Columbia (DC) and PA; in the South Atlantic, we include the U.S. territories of Puerto Rico (PR) and U.S. Virgin Islands (USVI); and in the Western Pacific, we include the U.S. territories of Guam (GU), American Samoa (AS), and the Northern Marianas Islands (NMI). Also, we created the Great Lakes region, which includes the states of OH and MI as well as cities in other states that border the Great Lakes and fall within 75 miles of their nearest Great Lake. 

As stated previously, the FOSS reports federal fisheries data at a city-level for exports and imports via ports of entry and state-level for commercially landed catch. The processed products database also aggregates data at the city-level via the address of the processing plant. For most of the regions described above, aggregating these data at the regional level was straightforward. Florida, however, straddles two regions (South Atlantic and Gulf) and was thus split in two parts: East-FL and West-FL. We identified cities that belonged to East-FL or West-FL with the aid of Google Gemini, an AI tool. We organized 196 Florida cities found in the processed products and trade data into a .csv file and provided the file to Gemini with the following prompt:

*“Hello, I have a task for you. I am providing a csv file of city names in the state of Florida, under the column name ‘PLANT_CITY’. Please find whether each city falls nearer to the Gulf coast or the Atlantic Coast of the state of Florida. In a new column named ‘PLANT_COAST’, please list the coast (either ‘ATLANTIC’ or ‘GULF’) nearest to the associated city. If a city is farther inland, please assign the coast nearest to that city. Thanks!”*

Gemini initially responded to this prompt cooperatively and outputted a dataset following the request. The tool described its methodology as determining the longitude of each city and classifying it as either greater than -81.5 degrees (closer to the Atlantic coast) or less than -81.5 degrees (closer to the Gulf coast). The tool also professed that it could not obtain longitude data for over 80 cities and thus classified their coasts as ‘UNKNOWN’. We sought to investigate the tool’s consistency in performing this task by ingesting the identical prompt used initially as well as the same .csv of florida cities. Strangely, the tool was not able to execute the task upon two consecutive requests made in separate web sessions, and instead issued the following response:

*“I am sorry, but I am unable to perform this task. I lack the ability to access geographical data and perform the necessary calculations to determine the distance of each city to a specific coast. I cannot access external geographical databases or APIs to find the coordinates of the cities or the coastlines. If you can provide a dataset with the latitude and longitude for each city, I may be able to help.”*

This response is indeed strange because the tool claims to be unable to find city coordinates, yet prior Gemini outlined its methodology which involved identifying city longitudes and comparing these against the longitude that splits Florida. Regardless of this inconsistency, we validated Gemini’s output by randomly sampling its ‘Atlantic’ coast classifications and ‘Gulf’ coast classifications. We evaluated ten of Gemini’s classifications for each coast and found no incorrect classifications, or 100% accuracy. For cities whose coasts were classified by Gemini as ‘Unknown’, we qualitatively evaluated their proximity to either coast using Google Maps and assigned the appropriate coast. This effort only applies to processed product and trade data as commercial landings data do not provide a city-level resolution; therefore, we classified commercial landings from the state of Florida to the South Atlantic region. Furthermore, commercial landings in the Great Lakes region only reflect the states of MI and OH. 

